### ISSUE TITLE
Ability to search for entries based off address sub-field (e.g. city).

### ISSUE THREAD

**Issue by gshade** [lindseydiloreto/craft-smartmap#13]
Doesn't seem like the plugin currently supports the ability to search for entries via something like:

``{% set query = craft.request.getParam('q') %}``
``{% set entries = craft.entries({ section: 'locations', search: 'address.city:' ~ query }) %}``

Where the query passed is the name of a city.

Let me know if I've set this up incorrectly though or if there's another way of getting some form of traditional Craft search working with the addresses (even if I need to query the field as a whole for the city name, etc).

**Comment by lindseydiloreto** [comment]
As of today's release (v2.3.0), this is now officially possible!

https://craftpl.us/plugins/smart-map/docs/filtering-entries-by-subfield-value
