### ISSUE TITLE
Problems with address search

### ISSUE THREAD

**Issue by paul-frost** [lindseydiloreto/craft-smartmap#15]
In Firefox on OS X 10..5 I put in a UK postcode into Zip code and I then have to click in another box and the suggested address comes up in a modal window, but I can't click on it before it disappears.
In Chrome, the modal appears over the address boxes, rather to the side like you show in the wiki. But it didn't fill in all the boxes with the info that was in the suggestion.
I'm not sure if that's due to the address structure being US focused rather than UK, where we have a different format for addresses:
Street
Town
County
Postcode
So perhaps it needs more flexible configuration options.

But what I would really like to see is a map (Google or Open Street Map), so I could see where the search had identified it and the option to be able to move the pin and fine tune a location that isn't a house in a street. An example is this addon for ExpressionEngine, http://dvt.ee/maps

**Comment by lindseydiloreto** [comment]
Internationalization support was added in v2.2.0, and rest of these items were included in v.2.0.0.

If you have any follow-up questions or comments, please email me at support@doublesecretagency.com
