### ISSUE TITLE
Directions not working anymore

### ISSUE THREAD

**Issue by br-designer** [lindseydiloreto/craft-smartmap#27]
After updating smartmap to v2.0.12, the directions feature stopped working. The link now shows up as "[current-url]no-address-coordinates". My location entries are still in craft and everything else works as usual.

What I was using:
` <a href="{{ craft.smartMap.directions(element.address, element.title) }}" target="_blank">Directions</a>`

My fix for now:
`<a href="https://maps.google.com?daddr={{ entry.address.street1 }}+{{ entry.address.city }}+{{ entry.address.state }}+{{ entry.address.zip }}" target="_blank">Directions</a>`

Thanks for your help in advance.

**Comment by lindseydiloreto** [comment]
Forgot to close this ticket, but this issue was fixed in [v2.0.13](https://craftpl.us/plugins/smart-map/change-log)
