### ISSUE TITLE
If address is undefined while rendering a map javascript throws an error

### ISSUE THREAD

**Issue by loweoj** [lindseydiloreto/craft-smartmap#29]
Attempting to render a map with an address fields blank leads to a syntax error: unexpected "," - where smartmap is assuming there will be co-ordinate values.

It would be great if an empty address field passed into craft.smartMap.map(*emptyAddressField*, mapOptions) didn't throw a confusing javascript error! Took me a while to figure out what was going on!

Maybe just fail silently?

Also, a method to check whether address is empty without having to loop through each field
{% if address.street1 is defined or address.street2 is defined of address.zip is defined %} ... etc.

**Comment by lindseydiloreto** [comment]
Thanks for the heads up! This has been fixed for the next release.

If an address field is lacking **both a latitude & longitude**, it will be ignored complete. Any results without a full set of coordinates will be omitted from the map entirely.

**Comment by lindseydiloreto** [comment]
> ... a method to check whether address is empty...

This is a great request, and I've added it for the next release. Thanks! :)

**Comment by lindseydiloreto** [comment]
Per this request, I've added "isEmpty" and "hasCoords" methods to the Address model...

https://craftpl.us/plugins/smart-map/docs/isempty-and-hascoords
