### ISSUE TITLE
Using CSV import to populate Address

### ISSUE THREAD

**Issue by nexflo** [lindseydiloreto/craft-smartmap#30]
Is there an easy way to use https://github.com/boboldehampsink/import or a custom plugin to import Addresses and let the plugin get the lat,lng as well?

**Comment by lindseydiloreto** [comment]
Not at the moment, but this is on the roadmap, with plans to address it very soon!

**Comment by nexflo** [comment]
Thanks Lindsey, 
tightly awaited over here :)

**Comment by lindseydiloreto** [comment]
@nexflo I've got a beta version of this ready to go... shoot me an email at support@doublesecretagency.com, and I'll send it over to you!

**Comment by romain-lgr** [comment]
Hi Lindsey, 
Great plugin!
I am also interested in this functionality. What is the status on this?
Thanks a lot.

**Comment by lindseydiloreto** [comment]
The beta version is solid, feel free to email support@doublesecretagency.com and I'll send you a copy. It handles compatibility with the Import plugin (and Export plugin) perfectly.

The only reason I haven't publicly released it yet... I'm trying to add a few more (unrelated) features before this version goes live.

**Comment by lindseydiloreto** [comment]
As of today's release (v2.3.0), Smart Map is now fully compatible with Import!

https://craftpl.us/plugins/smart-map/change-log
