### ISSUE TITLE
Static map URL without img tags?

### ISSUE THREAD

**Issue by KnutSv** [lindseydiloreto/craft-smartmap#31]
Would be great to be able to customize the markup when rendering static maps:
- Could use it with responsive images (picture-element)
- Could use it in meta tags

**Comment by KnutSv** [comment]
Nevermind, after looking through the source code I found out I could do it this way:

```php
{{ craft.smartMap.imgSrc(locations, options) }}
```

Don't think it's mentioned in the docs though?

**Comment by lindseydiloreto** [comment]
Good find, that's exactly right!

Thanks for pointing that out, I'll make sure to add it to the docs.

**Comment by lindseydiloreto** [comment]
Officially added to the docs. :+1: 

Thanks again!
