### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by Ramshackle-Jamathon** [lindseydiloreto/craft-smartmap#34]
{% paginate craft.entries.smartMapField(distanceParams).search(searchParam).limit(searchParamQuantity).order("publishDate") as entries %}
throws an CDbException while:

    {% set test = craft.entries.smartMapField(distanceParams).search(searchParam).limit(searchParamQuantity).order("publishDate") %}
 works perfectly

**Comment by Ramshackle-Jamathon** [comment]
full error code:
CDbException

CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause'. The SQL statement executed was: SELECT `elements`.`id`
FROM `craft_elements` `elements`
JOIN `craft_elements_i18n` `elements_i18n` ON elements_i18n.elementId = elements.id
JOIN `craft_content` `content` ON content.elementId = elements.id
JOIN `craft_smartmap_addresses` ON elements.id=craft_smartmap_addresses.elementId
JOIN `craft_entries` `entries` ON entries.id = elements.id
JOIN `craft_sections` `sections` ON sections.id = entries.sectionId
LEFT JOIN `craft_structures` `structures` ON structures.id = sections.structureId
LEFT JOIN `craft_structureelements` `structureelements` ON (structureelements.structureId = structures.id) AND (structureelements.elementId = entries.id)
WHERE ((((elements_i18n.locale = :locale) AND (content.locale = :locale)) AND (elements.archived = 0)) AND ((elements.enabled = 1) AND (elements_i18n.enabled = 1) AND (entries.postDate <= '2015-12-04 16:29:21') AND ((entries.expiryDate is null) OR (entries.expiryDate > '2015-12-04 16:29:21')))) AND (elements_i18n.enabled = 1)
GROUP BY `elements`.`id`
HAVING distance <= 75. Bound with :locale='en_us'

**Comment by Ramshackle-Jamathon** [comment]
It looks like Smart Map doesn't work with elementCriteriaModel and needs an entryModel

**Comment by lindseydiloreto** [comment]
Hmm, Smart Map definitely does work with an ElementCriteriaModel... looks like something might be causing trouble with the `pagination` tag.

Did this previously work in Craft 2.4?

**Comment by Ramshackle-Jamathon** [comment]
yeah I figured it did. I rolled back to craft2.4 and using the v2.21rc4 it worked. 

thanks for the assist!

**Comment by lindseydiloreto** [comment]
FWIW, you can use Smart Map 2.3 on Craft 2.4... The only change you need to make is this:

On **line 4** of `SmartMap_AddressFieldType.php`, change this:

    class SmartMap_AddressFieldType extends BaseFieldType implements IPreviewableFieldType

to this:

    class SmartMap_AddressFieldType extends BaseFieldType

The purpose of `implements IPreviewableFieldType` is specific to Craft 2.5, there's no harm at all in removing it for 2.4 compatibility.

**Comment by lindseydiloreto** [comment]
#### UPDATE

The pagination bug is officially fixed with the release of **Craft 2.5.2754** and **Smart Map 2.3.1**.
