### ISSUE TITLE
Map styles/stylers in options

### ISSUE THREAD

**Issue by codyjames** [lindseydiloreto/craft-smartmap#36]
First off, thanks for writing this plugin! It works very well and we'll be buying several licenses (we already have one) for about 7 different sites.

Anyway, I'm wondering how to pass styles to the map. Here is what I was expecting to work but it's throwing an error. 

```
{% set options = {
          height: 300,
          width: 1280,
          styles: {
             featureType: "all",
             stylers: [
               { saturation: -90 },
               { lightness: 50 }
             ]
          }
      } %}
{{ craft.smartMap.map(entry.locationAddress, options) }}
```

**Comment by lindseydiloreto** [comment]
Thanks, glad to hear it! :)

Many attributes can be passed in early, via Twig, but some attributes (like styles) can't be applied until the map has been rendered in JavaScript. Check out this page for a little more info:

>https://craftpl.us/plugins/smart-map/docs/customizing-after-the-map-is-rendered

After the map has been rendered on the page, you'll have certain JS objects available to you:

- `smartMap.map['smartmap-mapcanvas-1']` - the map object
- `smartMap.marker['smartmap-mapcanvas-1.17.myAddressField']` - a marker object
- `smartMap.infoWindow['smartmap-mapcanvas-1.18.myAddressField']` - an info bubble object

So the trick is, add your JS using something like `{% includejs %}` in Twig, and it will be applied to the map virtually instantaneously. There should really be no visible delay in your map styles being applied.

Hope that helps, let me know if you have any follow up questions!

**Comment by codyjames** [comment]
Sounds good. That'll do just fine. Thanks!
